services:
  postgres:
    image: postgres:15
    container_name: mbspro-postgres
    environment:
      POSTGRES_USER: mbspro
      POSTGRES_PASSWORD: mbspro
      POSTGRES_DB: mbspro
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mbspro -d mbspro"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  hapi:
    image: hapiproject/hapi:latest
    container_name: hapi
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-Xms512m -Xmx2g"
    restart: unless-stopped
